import pandas as pd
import io

# This string contains the raw data you provided
csv_data = """1,"DJ Maphorisa, DJ Tunez, Wizkid & Mavo","MONEY CONSTANT"
2,"CKay","BODY (danz) [feat. Mavo]"
3,"Famous PLuto & Zerrydl","Unto the Next"
4,"Somval","Come and See"
5,"Seyi Vibez","FUJI MOTO"
6,"OG Abbah","Wayyo Allah Na"
7,"Urban Chords","badman gangsta"
8,"Xploitcomedy","Soft life is calling (ise !)"
9,"Seyi Vibez & Trippie Redd","UP"
10,"Omah Lay","Waist"
11,"CHIZURUOKE","CHIKILI BOM BOM"
12,"Shallipopi","Over the Seas (feat. Focalistic)"
13,"Ayra Starr & Rema","Who’s Dat Girl"
14,"Champz","Champion Sound"
15,"Bella Shmurda","Appraisal"
16,"Withdkey","Dealermix"
17,"Ciza, Tems & Omah Lay","Isaka II (6am)"
18,"Kumba & Blazon","Achukuleke Bom Bom"
19,"Olga Myko","use me!!!!!!!"
20,"HypemanDJ Pablo","Ace of spade beat"
21,"Zlatan","Genesis (feat. Flavour)"
22,"Seyi Vibez","AMA"
23,"Paul CleverLee & Gerald Bishung","Anchor of My Strength"
24,"Mavo","Tumo Weto"
25,"Ice Prince","Oleku (feat. Brymo)"
26,"Rema","FUN"
27,"Poco Lee, Mavo & Diamond Boy","ENJOYMENT"
28,"Xploitcomedy","Soft Life Is Calling Ise (Spirit Cut)"
29,"Rybeena & Joeboy","Adunni"
30,"Slimcase & King Soundboi","Ko Skary Mo"
31,"JFS music","Dry Wave (feat. King Tone SA & Soa mattrix)"
32,"Kolaboy & Evado","Oga Eme"
33,"TUFF KING","Nkemakonam"
34,"Mavo","Shakabulizzy"
35,"Sis. Agatha Moses","Thank You"
36,"Brown Joel & Jeriq","Shayo"
37,"Kodak Black & Don Toliver","Who You Seeing Tonight"
38,"Nicki Minaj","Beez In The Trap (feat. 2 Chainz)"
39,"Masego","Unhinged"
40,"Tyla","CHANEL"
41,"ODUMODUBLVCK & Modenine","IF YOU LIKE GYM"
42,"EMIN & JONY","Камин"
43,"Disturbing F, FBeatz & Neeza","Salam (Fbeatz Version)"
44,"Adekunle Gold","Many People"
45,"Savio Nwa Otu","Consider (feat. Sparkle Tee)"
46,"Phyno","Ask of Me"
47,"FOLA","caricature"
48,"Rybeena","Spaghetti"
49,"BoyPee","Choice"
50,"DJ Tunez, Wizkid & ODUMODUBLVCK","EASY WITH ME"
51,"FOLA","you"
52,"Eminem","Mockingbird"
53,"Hamisu Breaker","Ihsan Amarya"
54,"4 Non Blondes","What's Up?"
55,"Seyi Vibez & Olamide","FUJI PARTY"
56,"Sarz, Asake, Wizkid & Skillibeng","Getting Paid"
57,"ZAKIN MA AIKI RK","Fadima Ba a kai ku girmaba"
58,"Dami Drizzy","Amin"
59,"EazyTee8589","Mina nawe"
60,"BNXN","Laye Mi"
61,"Rg HusslaDid","Nuru"
62,"Mightyyout & Davido","I Know"
63,"Black Eyed Peas & Shakira","GIRL LIKE ME"
64,"Ta Liebe","Hands on a Billi"
65,"Josh Belter","BAMBI"
66,"Lana Del Rey","Cinnamon Girl"
67,"Hotkid","Better Days"
68,"DJ Bomber","Killer Bean (Amapiano)"
69,"Hairat Abdullahi","Sanyin Idanuna (Wata Shida)"
70,"Vicoka","SPIRIT (feat. Wizard Chan)"
71,"Arctic Monkeys","I Wanna Be Yours"
72,"NF","FEAR"
73,"Fireboy DML","Dopamine"
74,"Spirit-Boyz & Sedii_M","Ghetto 44  (feat. PowerpuffBoii)"
75,"Zinoleesky","CELINE DION"
76,"MaWhoo, GL_Ceejay & Thukuthela","Bengicela (feat. Jazzworx)"
77,"Dave & Tems","Raindance"
78,"ODUMODUBLVCK, Davido & Seun Kuti","GROOVING"
79,"Ola Tok","Whobimostor"
80,"FOLA","bye bye"
81,"FOLA","healer"
82,"FOLA & Victony","golibe"
83,"Kidd Carder","Do Better"
84,"Cloudee","Blessings"
85,"Nasty C","SMA (feat. Rowlene)"
86,"NerdFND & South Plxya","Mama (feat. Iconic Keyz)"
87,"Ciza, Jazzworx & Thukuthela","Isaka (6am)"
88,"Seyi Vibez","HOW ARE YOU"
89,"Khalil Harrison & Tyler ICU","Jealousy (feat. Leemckrazy & Ceeka RSA)"
90,"Sis. Agatha Moses","Top Nigerian Praise Part 2"
91,"ODUMODUBLVCK","INDUSTRY MACHINE"
92,"Stahgee, Feladehusla & Aguero Banks","Dying Minute"
93,"ODUMODUBLVCK & Wizkid","BIG TIME"
94,"Khenyzee","Facetime 12(Deluxe Edition Pro) (feat. Zoro Swagbag)"
95,"Gracie Abrams","I Love You, I'm Sorry"
96,"Cazulee","For You"
97,"Caften & Highstarlavista","Nwannem"
98,"Alex Warren","Ordinary"
99,"Nasty C & T.I.","All In"
100,"EeQue, Pcee & Royal Musiq","Ke Wave"
101,"JAZZWRLD, Thukuthela & Babalwa M","uValo (feat. Dlala Thukzin)"
102,"FOLA & Young Jonn","disco"
103,"Danfo Drivers","Danfo Driver (Hip Hop Mix) [feat. Noah]"
104,"Davido","With You (feat. Omah Lay)"
105,"Meek Mill","HOW FAR WE CAME"
106,"Goon Flavour, Master KG & Eemoh","Ngishutheni"
107,"Blaqbonez","Despacito (feat. FOLA)"
108,"Mavo","Shakabulizzy (feat. Davido) [Remix]"
109,"Oberz","Oh No (feat. FOLA)"
110,"Sis. Ifeoma Ezeorah","OKU NERE ERE"
111,"Teee dollar","Money Moves"
112,"Chella","CHELLA CHANT"
113,"6uff","IDI AMIN"
114,"DJ Maphorisa, Xduppy & Enny Man Da Guitar","Dlala Ka Yona (feat. Focalistic, Ricky Lenyora, Uncool MC & Mellow & Sleazy)"
115,"EmmaOMG","E Ti Tobi To (feat. The OhEmGee Choir, Pelumi Deborah & BBO) [Live]"
116,"Ruhdee","Amen"
117,"Sarz, ODUMODUBLVCK, Shallipopi, Theodora & Zeina","Mademoiselle"
118,"P-Square","Bizzy Body"
119,"Phyno","Fada Fada (Ghetto Gospel) [feat. Olamide]"
120,"St Anointed","My Story (feat. Zyno Topboy) [Remix]"
121,"Ruger","Muhammad Ali (Can't Relate)"
122,"Barry Jhay","BLOOD OF THE LAMB"
123,"Akon","Lonely"
124,"Okalichalu Ibe Dynamic Group","Onu Riri Udene"
125,"Bella Shmurda","Upgrade"
126,"Gunna","wgft (feat. Burna Boy)"
127,"Kedjevara","Ça fait mal"
128,"Mavo","Escaladizzy (feat. WAVE$TAR)"
129,"Ayo Maff","TENSION"
130,"Myztro & Leehleza","Tobetsa 3.0 (feat. ShaunMusiq & Ftears)"
131,"6uff","PRODIGY"
132,"Cleffy","Meet you at the Graveyard"
133,"Pcee","Gabriella (feat. Officixl Rsa)"
134,"YNW Melly","Suicidal"
135,"Sojaboy","Kauna Nabaki"
136,"Solomon Ray","Find Your Rest"
137,"Faith Captain","Oshimiri Atata (Live)"
138,"T.I BLAZE & Llona","Lonely Road"
139,"Boy Muller","God Abeg"
140,"Ken Erics","Nwa Di Mma (feat. Mobass)"
141,"Vigro Deep, Zee Nxumalo & Ch'cco","Bhampa"
142,"Jeriq & Minz","DJ GO TIRE"
143,"Adekunle Gold","Temptation"
144,"KCee & Zoro Swagbag","Show Off"
145,"Odeal & Wizkid","N.I.T.S (feat. Wizkid)"
146,"DJ Maphorisa & Kabza De Small","Hamba Haa (feat. Nobantu Vilakazi & Young Stunna)"
147,"Sola Allyson","Ìgbà Ìrànwọ́"
148,"Wale, Teni & Seyi Vibez","YSF"
149,"Mavo & Shallipopi","Escaladizzy II (feat. Zlatan & Ayra Starr)"
150,"Spirit-Boyz, Sedii_M & Malemon","Coke Water"
151,"Burna Boy","Love"
152,"New West","Those Eyes"
153,"Future","WAIT FOR U (feat. Drake & Tems)"
154,"Outdoor DJz","Slide (Orignal) (feat. Tskay de Musiq, Bepa De Musiq, Maltez, Ocean Biller & Major Traze)"
155,"Olamide, Seyi Vibez, Asake & Young Jonn","99 (feat. Daecolm)"
156,"Chief Priest & Zoro Swagbag","Chibuike"
157,"Doublegrace","Odera (feat. Somval)"
158,"Commissioner Dj Wysei","Money Good"
159,"Young Thug","Miss My Dogs"
160,"Benzoo","Izolo (feat. Bukzin Keyz, Sizwe Alakine, Bob Mabena, Mid9t & Officixl RSA)"
161,"Monaky & Jeriq","7 Grams"
162,"Rybeena & Shoday","Gaddem"
163,"NURUDDEEN UKK","Mumtaz (feat. Abdul D One)"
164,"Tmizzy Mrhorrizen","Hunter Boys"
165,"BBO","My God"
166,"MC Levin","Sua Amiga Vou Sarrar"
167,"Cali Swag District","Teach Me How to Dougie"
168,"Monaky","The Goat"
169,"Gunna","let it breathe (feat. Roddy Ricch)"
170,"SAMAD","Tomorrow (Spiritual Version)"
171,"Dami","Dopamine (Cover)"
172,"Spyki","Ofeke"
173,"Chii_machine","Original iyoo (feat. Sparkle Tee & Beepee D Rapgod)"
174,"Prombwoy","Abagana"
175,"Dr. Sikiru Ayinde Barrister","Iku / Wole / Ola / Love in Tokyo"
176,"Deborah Ajayi","BASKET OF PRAISE"
177,"Hotkid","Why?"
178,"Kabza De Small, DJ Maphorisa & Ami Faku","Asibe Happy"
179,"R. City","Locked Away (feat. Adam Levine)"
180,"Kendrick Lamar","LOVE. (feat. Zacari)"
181,"Black Sherif","Sacrifice"
182,"Sojaboy","Habibi"
183,"DJ Tunez, Wizkid & FOLA","One Condition"
184,"Gunna","turned your back"
185,"Zeak","Iyi (feat. King Prof Obewe)"
186,"Famy","Ava"
187,"FloyyMenor & Cris MJ","Gata Only"
188,"Tkandz & CXSPER","NOW OR NEVER"
189,"Ugoccie","Achalugo"
190,"Burna Boy","Real Life (feat. Stormzy)"
191,"FAVE","Baby Riddim"
192,"Chief Michael Udegbi","Akana Akwukwo Ogwu"
193,"Asake & Tiakola","BADMAN GANGSTA"
194,"Lui Cruz","Wele Dance (feat. Berri-Tiga)"
195,"Joshua Baraka","Wrong Places"
196,"Emanvee","NO ONE TO CALL"
197,"The Hit Maker","Elon Musk (Amapiano Transmission)"
198,"DJ Malvado & DJ Aka-m","Mussulo (feat. Dody)"
199,"King Willonius","Move Bitch (1973)"
200,"Famous PLuto, Shallipopi & Zerrydl","Ewo"
"""

# Read the CSV data using pandas
# The input format is: Index, Artist, Song Name
df = pd.read_csv(io.StringIO(csv_data), header=None, names=["Index", "Artist", "Song Name"])

# Drop the 'Index' column as it is not needed for the playlist maker
df = df.drop(columns=["Index"])

# Reorder columns to put Song Name first (optional, but looks cleaner)
df = df[['Song Name', 'Artist']]

# Export to Excel
filename = "songs.xlsx"
df.to_excel(filename, index=False)

print(f"Successfully created '{filename}' with {len(df)} songs.")